### ISSUE TITLE
docs not generating correctly

### ISSUE THREAD

**Issue by detiber** [ftl-toolbox/lib_openshift#1]
@tbielawa @abutcher seeing issues when trying to build the docs for this, any insights would be great. 

I generated the rst files using: `sphinx-apidoc -o docs -f lib_openshift`
and then tried to create html output using: `make -C docs html`

**Comment by timlnx** [comment]
I got it to build after a little debugging. The issue **on my machine** was a masked import error **inside** the code. I opened a new python repl and updated my `sys.path` to include `/tmp/tmp.D5NnB8ifbx/lib_openshift/` (I cloned it into `mktemp -d`). You can see the missing module exception in this way:

```
In [1]: import os; import sys

In [2]: sys.path.insert(0, '/tmp/tmp.D5NnB8ifbx/lib_openshift')

In [3]: import lib_openshift.models
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-bcb527ed01b8> in <module>()
----> 1 import lib_openshift.models

/tmp/tmp.D5NnB8ifbx/lib_openshift/lib_openshift/__init__.py in <module>()
    334 
    335 # import apis into sdk package
--> 336 from .apis.api_api import ApiApi
    337 from .apis.apis_api import ApisApi
    338 from .apis.apisautoscaling_api import ApisautoscalingApi

/tmp/tmp.D5NnB8ifbx/lib_openshift/lib_openshift/apis/__init__.py in <module>()
      2 
      3 # import apis into api package
----> 4 from .api_api import ApiApi
      5 from .apis_api import ApisApi
      6 from .apisautoscaling_api import ApisautoscalingApi

/tmp/tmp.D5NnB8ifbx/lib_openshift/lib_openshift/apis/api_api.py in <module>()
     27 
     28 from ..configuration import Configuration
---> 29 from ..api_client import ApiClient
     30 
     31 

/tmp/tmp.D5NnB8ifbx/lib_openshift/lib_openshift/api_client.py in <module>()
     21 from __future__ import absolute_import
     22 from . import models
---> 23 from .rest import RESTClientObject
     24 from .rest import ApiException
     25 

/tmp/tmp.D5NnB8ifbx/lib_openshift/lib_openshift/rest.py in <module>()
     25 import json
     26 import ssl
---> 27 import certifi
     28 import logging
     29 

ImportError: No module named certifi
```

How to fix? First, setup:

```
$ echo $PYTHONPATH 
/home/tbielawa/.local/lib/python2.7/site-packages/:/home/tbielawa/lib/python/
```

Note how that's a local python lib dir there first `~tbielawa/.local/lib/python2.7`. That dir tree is created if you use the `pip` commands `--user` option flag.

I switched back to the root directory of the git checkout and ran this command:

```
pip install --user .
```

This installed all of the lib requirements given in the `setup.py`s `REQUIRES` variable. Now, update your `PYTHONPATH` and then switch back into the docs dir and run the build command like normal:
- Update your PYTHONPATH to include the local dir, `export PYTHONPATH=~/.local/lib/python2.7/site-packages/:$PYTHONPATH`. 

```
cd docs
make clean
make html && xdg-open _build/html/index.html
```

You can see example results on my site here: http://lnx.cx/~tbielawa/lib_openshift/py-modindex.html

**Comment by timlnx** [comment]
In short, the fix is to install all of the required deps' because sphinx-apidoc needs to be able to import the code to read the docstrings. Sphinx couldn't import the module, ergo, the docs couldn't build.

Side note, any side-effects will be ran on import if present in imported code (not a problem in this case).

**Comment by detiber** [comment]
@tbielawa so, the steps I took to try and install involved the following:

```
virtualenv venv
source ./venv/bin/activate
python setup.py develop
```

Shouldn't that also have satisfied the import issue? Or is there something that Sphinx or make is doing that invalidates the virtualenv?

**Comment by detiber** [comment]
I figured it out:

```
pip install -r docs_requirements.txt
make html SPHINXBUILD="python $(which sphinx-build)"
```

make executes sphinx-build which invokes the system python interpreter.
